### ISSUE TITLE
New Logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [Ismaestro/angular7-example-app#34]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![angular](https://user-images.githubusercontent.com/33461607/48151718-96850e00-e2f4-11e8-83fa-79c012f44b17.png)
there I designed it using the icon from the letter A. and the letter A I took from the first letter of the word Angular. and I also use letter 7 to be an icon to give meaning that this is Angular 7

**Comment by Ismaestro** [comment]
Hey! 

First of all, thanks for the effort, just one thing. We should not use the angular version, because in 6 months there will be a new one, so we'll have to update the logo. Maybe you take the angular logo and modify it a little bit for this project (I mean the basics).

?

BR

**Comment by mansya** [comment]
how about this sir? I hope this is good. because I slightly modified the basic logo. but you can choose the color you like.
![angular](https://user-images.githubusercontent.com/33461607/48300773-af203e80-e515-11e8-9782-6ced92711dd5.png)

**Comment by Ismaestro** [comment]
That number 3 would be great!

Can you send me a PNG file with it?

**Comment by Ismaestro** [comment]
I've made some changes but the merge request is done.

Thanks!
