### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by omsun123** [Ismaestro/angular7-example-app#39]
This is what i tried 
`dev@dev-VirtualBox:~/Documents/angular-material-ui$ docker build -t angular .
Sending build context to Docker daemon  292.9MB
Step 1/12 : FROM node:8-alpine as builder
8-alpine: Pulling from library/node
4fe2ade4980c: Already exists 
9c94b1665db9: Pull complete 
9b413d1ce95e: Pull complete 
Digest: sha256:dfc36646eddf67cb2e18d9be1cdecb5ead4907b0593297bdc471f4e90d698d89
Status: Downloaded newer image for node:8-alpine
 ---> 9395a05e4ef9
Step 2/12 : COPY package.json package-lock.json ./
 ---> 3e7444a0471e
Step 3/12 : RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
 ---> Running in ef7d026b5463
npm WARN using --force I sure hope you know what you are doing.
Removing intermediate container ef7d026b5463
 ---> ae16923b0e75
Step 4/12 : RUN npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app
 ---> Running in e5641a0d21f5
`

my docker not proceeding after this.

**Comment by Ismaestro** [comment]
I removed docker support. If you need info about it check [this link](https://dev.to/avatsaev/create-efficient-angular-docker-images-with-multi-stage-builds-1f3n).
