### ISSUE TITLE
I am trying to add my firebase account, but the image files are not available in it and hence the app does not work properly. Please suggest how do I upload the files in my firebase account.

### ISSUE THREAD

**Issue by hitzgit** [Ismaestro/angular7-example-app#41]
### Bug Report or Feature Request (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [ ] feature request

**Comment by Ismaestro** [comment]
Just go to your firebase console. Then go, Storage -> Upload file. You should see something like this (in your language):

<img width="1115" alt="screenshot 2019-02-13 at 10 47 44" src="https://user-images.githubusercontent.com/10084945/52702651-e242f580-2f7c-11e9-8346-6d2b84a5769b.png">

**Comment by hitzgit** [comment]
This is not available in the storage folder. I followed the step to deploy  to firebase not sure what step is missing.

**Comment by Ismaestro** [comment]
Provide me a screenshot. What do you mean with "This is not available in the storage folder."? This has nothing to do with the deploy...

**Comment by hitzgit** [comment]
By This I mean is the images that you shared in screenshot.

![capture](https://user-images.githubusercontent.com/46263857/52705923-1da7e900-2faa-11e9-8837-65590ca5f998.JPG)

**Comment by hitzgit** [comment]
To be precise.. I want to use my own private firebase account and add more image files if i want to.. Can I do like that?

**Comment by Ismaestro** [comment]
The images that you saw in my screenshot are images uploaded in the project with **my** firebase account, obviously you won't see them in your account.

If you want to use your own firebase project you should upload your own files in your account and use them in your application the same way I do on mine. Hope this helps!

BR

**Comment by hitzgit** [comment]
Yes i got you. Thanks alot.
